services:
  app:
    container_name: app
    build: ./backend
    ports:
      - "$PUBLIC_BACKEND_PORT:$PUBLIC_BACKEND_PORT"
    environment:
      - PUBLIC_HOSTNAME=$PUBLIC_HOSTNAME
      - PUBLIC_BACKEND_PORT=$PUBLIC_BACKEND_PORT
      - FRONTEND_PORT=$FRONTEND_PORT
      - ENV=$ENV

  web:
    container_name: web
    build: ./frontend
    ports:
      - "$FRONTEND_PORT:$FRONTEND_PORT"
    environment:
      - PUBLIC_HOSTNAME=$PUBLIC_HOSTNAME
      - PUBLIC_BACKEND_PORT=$PUBLIC_BACKEND_PORT
      - PORT=$FRONTEND_PORT
    depends_on:
      - app

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   restart: always
  #   depends_on:
  #     - app
  #     - web
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./certs:/etc/nginx/certs:ro
  #   ports:
  #     - "80:80"
  #     - "443:443"