services:
  app:
    container_name: app
    image: ghcr.io/NAMESPACE/IMAGE_NAME:latest
    ports:
      - "$PUBLIC_BACKEND_PORT:$PUBLIC_BACKEND_PORT"
    environment:
      - PUBLIC_HOSTNAME=$PUBLIC_HOSTNAME
      - PUBLIC_BACKEND_PORT=$PUBLIC_BACKEND_PORT
      - FRONTEND_PORT=$FRONTEND_PORT

  web:
    container_name: web
    image: ghcr.io/NAMESPACE/IMAGE_NAME:latest
    ports:
      - "$FRONTEND_PORT:$FRONTEND_PORT"
    environment:
      - PUBLIC_HOSTNAME=$PUBLIC_HOSTNAME
      - PUBLIC_BACKEND_PORT=$PUBLIC_BACKEND_PORT
      - FRONTEND_PORT=$FRONTEND_PORT