services:
  app:
    container_name: app
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PUBLIC_BACKEND_URL=http://localhost/api
      - BACKEND_PORT=8000
      - FRONTEND_URL=http://localhost
      - ENV=docker
    networks:
      - customnet

  web:
    container_name: web
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - PUBLIC_BACKEND_URL=http://localhost/api
      - PORT=5173
    depends_on:
      - app
    networks:
      - customnet

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - app
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    environment:
      - BACKEND_PORT=8000
      - FRONTEND_PORT=5173
    networks:
      - customnet

networks:
  customnet:
    driver: bridge